---
- name: Docker configure in EC2 Machine
  hosts: all
  become: true
  connection: ssh
  tasks: 
    - name: updating the new EC2 machine
      apt:
        upgrade: yes
      become: yes
      become_user: root

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes
      become_user: root

    - name: Start Docker service
      service:
        name: docker
        state: started
      become: yes
      become_user: root
