---
- name: Docker configure in EC2 Machine
  hosts: all
  become: true
  tasks:
    - name: updating the new EC2 machine
      # Use apt instead of yum for Debian-based systems
      command: sudo apt update

    - name: Install Docker
      # Use apt instead of yum for Debian-based systems
      command: sudo apt install docker.io

    - name: Start Docker service
      command: sudo systemctl start docker


