---
- name: Docker configure in EC2 Machine
  hosts: all
  become: yes
  become_user: ubuntu
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started



